#!/usr/bin/env bash
# Run this on your own machine (it needs normal internet access).
# Pulls real, verified, freely-licensed script documents into sample-scripts/.
set -e
cd "$(dirname "$0")"

mkdir -p 01-theater-shakespeare-tragedy 02-theater-tragedy 03-theater-comedy \
         04-movie-thriller 05-movie-comedy 06-tv-anthology-thriller \
         07-sitcom-comedy 08-monologue-speech

# 01 — Macbeth (Shakespeare, 1606) — Project Gutenberg eBook #1129 — public domain
curl -L -o 01-theater-shakespeare-tragedy/macbeth_shakespeare.txt \
  "https://www.gutenberg.org/ebooks/1129.txt.utf-8"

# 02 — Riders to the Sea (J.M. Synge, 1904) — Project Gutenberg eBook #994 — public domain
curl -L -o 02-theater-tragedy/riders_to_the_sea_synge.txt \
  "https://www.gutenberg.org/ebooks/994.txt.utf-8"

# 03 — The Importance of Being Earnest (Oscar Wilde, 1895) — Project Gutenberg eBook #844 — public domain
curl -L -o 03-theater-comedy/importance_of_being_earnest_wilde.txt \
  "https://www.gutenberg.org/ebooks/844.txt.utf-8"

# 04 — Night of the Living Dead (1968) screenplay by Romero & Russo — public domain (no copyright notice on release)
curl -L -o 04-movie-thriller/night_of_the_living_dead_1968_script.pdf \
  "https://assets.scriptslug.com/live/pdf/scripts/night-of-the-living-dead-1968.pdf"

# 05 — His Girl Friday (1940) screenplay by Charles Lederer — public domain (non-renewal; underlying
#       1928 play "The Front Page" entered PD Jan 1 2024 too)
curl -L -o 05-movie-comedy/his_girl_friday_1940_script.txt \
  "https://www.dailyscript.com/scripts/His%20Girl%20Friday.txt"
# Backup PDF if the line above 404s:
# curl -L -o 05-movie-comedy/his_girl_friday_1940_script.pdf \
#   "https://cdn.devilslane.com/screenplays/His_Girl_Friday_1940_Screenplay.pdf"

# 06 — Tales of Tomorrow: "Frankenstein" (1952) — likely public domain, but NO real script exists,
#       only the broadcast video and a rough machine-generated caption transcript:
curl -L -o 06-tv-anthology-thriller/frankenstein_1952_video.mp4 \
  "https://archive.org/download/Tales_of_Tomorrow_16_Frankenstein/tales_of_tomorrow_16_frankenstein.mp4"
curl -L -o 06-tv-anthology-thriller/frankenstein_1952_autogenerated_transcript.txt \
  "https://archive.org/download/Tales_of_Tomorrow_16_Frankenstein/tales_of_tomorrow_16_frankenstein.autogenerated.txt"

# 07 — Sitcom comedy: no public script document found (see README) — nothing to download yet.

# 08 — The Gettysburg Address (Lincoln, 1863) — public domain
curl -L -o 08-monologue-speech/gettysburg_address_lincoln.html \
  "https://www.abrahamlincolnonline.org/lincoln/speeches/gettysburg.htm"

echo "Done. Check README.md for the two categories (06, 07) that still need a decision."
